config/routes.rb
Rails.application.routes.draw do

  resources :addresses, only: [:new, :create, :index]

  root 'addresses#index'

end

app/models/address.rb
class Address < ActiveRecord::Base

  validates :name, :street, :city, :state, :zip, presence: true
  validates :name, uniqueness: true, length: {within: 3..35}

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
    @addresses = Address.all
  end

  def new
    @address = Address.new
    render layout: 'fancybox'
  end

  def create
    @address = Address.new(address_params)

    if @address.save
      @addresses = Address.all
    else
      @error_message = error_messages(@address)
      @error_message ||= 'Unable to create new address.'
    end
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private

  def address_params
    params.require(:address).permit(:name, :street, :city, :state, :zip)
  end

  def error_messages(record)
    return nil unless record.errors
    record.errors.full_messages.map { |msg| msg }.join('<br />')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/create.js.haml
- if @error_message
  $('#edit_address_errors').html(alert_box('danger', "#{@error_message.html_safe}"))
- else
  $('#list_addresses').html("#{escape_javascript(render partial: 'addresses/partials/list_addresses')}")
  $.fancybox.close();

app/views/addresses/index.html.haml
%h1 Addresses

= link_to 'New Address', new_address_path, data: {fancybox_width: 350}, class: 'fancybox btn btn-success'
%br/
%br/

#list_addresses
  = render 'addresses/partials/list_addresses'

app/views/addresses/new.html.haml
.modal-content
  .modal-header
    %button.close{href: 'javascript:;', onclick: '$.fancybox.close();', type: 'button'}
      %span{'aria-hidden' => 'true'} x
      %span.sr-only Close
    %h3 New Address
    .modal-body
      #edit_address_errors
      = form_for @address, html: {id: 'new_address', class: 'form-horizontal', role: 'form', data: {remote: true}} do |f|
        .form-group
          .col-sm-3
            Name:
          .col-sm-9
            = f.text_field :name, id: 'name', class: 'form-control'
        .form-group
          .col-sm-3
            Street:
          .col-sm-9
            = f.text_field :street, id: 'street', class: 'form-control'
        .form-group
          .col-sm-3
            City:
          .col-sm-9
            = f.text_field :city, id: 'city', class: 'form-control'
        .form-group
          .col-sm-3
            State:
          .col-sm-9
            = f.text_field :state, id: 'state', class: 'form-control'
        .form-group
          .col-sm-3
            Zip:
          .col-sm-9
            = f.text_field :zip, id: 'zip', class: 'form-control'
        .form-group
          .col-sm-9.col-sm-offset-3
            = f.submit 'Save', class: 'btn btn-success'

app/views/addresses/partials/_list_addresses.html.haml
- @addresses.each do |address|
  = address.name
  %br/
  = address.street
  %br/
  #{address.city}, #{address.state} #{address.zip}
  %br/
  %br/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fpost
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/layouts/fancybox.html.haml
!!!
%html
  %body.overflowhidden
    = yield
    